### ISSUE TITLE
Error since last Update

### ISSUE THREAD

**Issue by MacVille** [FaserF/ha-rewe#12]
### The problem

The HA-Core Logs shows Error from the Integration after Restart of HA.

The Following Error gets Logged:

```
Logger: homeassistant
Source: helpers/entity_platform.py:428
First occurred: 01:00:07 (1 occurrences)
Last logged: 01:00:07

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    tasks = [
TypeError: 'ReweSensor' object is not iterable
```

### What version of Home Assistant Core has the issue?

core-2023.3.6

### What version of Rewe Integration has the issue?

2023.03.0

### What type of installation are you running?

Home Assistant OS

**Comment by FaserF** [comment]
Does the error still exist with the latest HA and latest rewe integration release?

**Comment by MacVille** [comment]
No this Error message is no longer there.
