### ISSUE TITLE
Custom Lovelace card for use with this integration

### ISSUE THREAD

**Issue by schblondie** [FaserF/ha-rewe#24]
### The request

Hey, I have made a lovelace card which would make the usage of your integration a lot more convenient.
Its shows the products in their respective categories and allows to add the products to a shopping list (todo list)
![Screenshot 2024-03-19 225524](https://github.com/FaserF/ha-rewe/assets/80481720/5c9525a0-74b0-4e38-96e7-264ba4d619d0)

It supports configuration through a GUI, which is currently not Lovelace styled, would need help there tbh.
![image](https://github.com/FaserF/ha-rewe/assets/80481720/066c4e3e-ce31-4a2c-9b11-3ec60c904dc5)

I can be found here: https://github.com/schblondie/ha-rewe-discounts-card

I would love to be added to example lovelace cards like the markdown one [KrizzeOne](https://github.com/FaserF/ha-rewe?tab=readme-ov-file#sample-lovelace-card) provided and be happy from contributions from all of you to expand on this card.

**Comment by FaserF** [comment]
Thank you for your work and input! I have added it to the readme :)

**Comment by FaserF** [comment]
Hi, I dropped a new release and refactored the whole integration. If you are still interested in the integration, I am happy to see the lovelace card adapted for the new release 👍🏼
